# Generated by Django 2.0.6 on 2019-02-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_fn', models.CharField(default='', max_length=200)),
                ('child_ln', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mom_fn', models.CharField(default='', max_length=200)),
                ('mom_ln', models.CharField(default='', max_length=200)),
                ('mom_pn', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_mom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwApp.Mom'),
        ),
    ]
